console.log("=============n-1==================");
let array = ["Facebook", "Google", "Microsoft", "Apple", "IBM", "Oracle", "Amazon"];
console.log(array);
 array.sort();
 console.log(array);
 console.log("===========n-2===================");
 let array1 = ["Facebook", "Google", "Microsoft", "Apple", "IBM", "Oracle", "Amazon"];
 console.log(array1);
 const reversed= array1.reverse();
 console.log(reversed);
 console.log("===========n-3==================");
 let array2 = ["Facebook", "Google", "Microsoft", "Apple", "IBM", "Oracle", "Amazon"];
 console.log(array2);
 const shifted= array2.shift();
 console.log("Ehnii index:",shifted);
 console.log("==========n-4==================");
 let array3 = ["Facebook", "Google", "Microsoft", "Apple", "IBM", "Oracle", "Amazon"];
 console.log(array3);
 const spliced=array3.splice(0,3);
 
 console.log(spliced);