let array = ["Facebook", "Google", "Microsoft", "Apple", "IBM", "Oracle", "Amazon"];
let arr = [];
array.sort();
console.log(array);
arr = array;
let reversed = array.reverse();
console.log(reversed);
arr.splice(1, 1);
console.log(arr);
array.splice(3, 1);
console.log(array);